name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
            
      - name: Build release
        run: ./gradlew assembleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"

      - uses: actions/upload-artifact@v2
        with:
          name: Signed app bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          if-no-files-found: error

  deploy:
    name: Deploy to GitHub Releases
    needs: build
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Get the APK
        id: get_apk
        uses: actions/download-artifact@v2
        with:
          name: app

      - name: Publish the APK to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with:
          prerelease: true
          asset_name: pinning-signed.apk
          file: ${{steps.sign_app.outputs.signedReleaseFile}}
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
